services:
    _defaults:
        autowire: false
        autoconfigure: false
        public: false

    unglin_land.role.entity_manager:
        class: Doctrine\Common\Persistence\ObjectManager
        factory: ["@doctrine", "getManagerForClass"]
        arguments: 
            - UnglinLandUserBundle:UnglinRole
        
    unglin_land.role.doctrine_orm_repository:
        class: UnglinLand\UserBundle\Model\Doctrine\ORM\Repository\UnglinRoleRepository
        factory: ["@unglin_land.role.entity_manager", "getRepository"]
        arguments: 
            - UnglinLandUserBundle:UnglinRole
