services:
    _defaults:
        autowire: false
        autoconfigure: false
        public: false

    unglin_land.role.manager:
        class: UnglinLand\UserModule\Manager\UnglinRoleManager
        public: true
        arguments:
            - "@unglin_land.role.mapper"
            - "@logger"
